version: "1"

# Template metadata
name: loki
description: Grafana Loki is a horizontally scalable, highly available log aggregation system inspired by Prometheus, designed to be cost-effective and easy to operate.
icon: https://raw.githubusercontent.com/grafana/loki/main/docs/sources/logo.png
category: monitoring
tags:
  - monitoring
  - logs
  - logging
  - observability
  - grafana

# Supported versions
versions:
  - "2.9.0"
  - "2.8.0"
  - "main"
defaultVersion: "2.9.0"

# Service definitions
services:
  - name: loki
    type: web
    image: "grafana/loki:${VERSION}"
    ports:
      - port: 3100
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    env:
      - key: TZ
        default: "UTC"
        configurable: true
        description: Timezone for the container
    volumes:
      - name: loki-data
        path: /loki
        size: 20480
    health_check:
      type: http
      path: /ready
      port: 3100
      initial_delay: 15
      interval: 30
      timeout: 10
      retries: 3
    cpu: 200
    memory: 512
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 3100
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
