version: "1"

# Template metadata
name: plane
description: Plane is an open-source project management tool offering issue tracking, sprints, cycles, and modules as a Jira alternative.
icon: https://raw.githubusercontent.com/makeplane/plane/master/web/public/plane-logo.svg
category: project
tags:
  - project-management
  - issue-tracking
  - jira-alternative
  - agile
  - kanban

# Supported versions
versions:
  - "v0.20"
  - "v0.19"
  - "latest"
defaultVersion: "v0.20"

# Service definitions
services:
  - name: plane-web
    type: web
    image: "makeplane/plane-frontend:${VERSION}"
    ports:
      - port: 3000
    env:
      - key: NEXT_PUBLIC_API_BASE_URL
        configurable: true
        description: URL of the Plane API service
      - key: NEXT_PUBLIC_DEPLOY_URL
        configurable: true
        description: URL where Plane is deployed
    health_check:
      type: http
      path: /
      port: 3000
      initial_delay: 30
      interval: 30
      timeout: 10
      retries: 3
    cpu: 200
    memory: 512
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 3000
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system

  - name: plane-api
    type: web
    image: "makeplane/plane-backend:${VERSION}"
    ports:
      - port: 8000
    env:
      - key: SECRET_KEY
        generator: password
        description: Django secret key
      - key: DATABASE_URL
        configurable: true
        description: PostgreSQL connection string
      - key: REDIS_URL
        configurable: true
        description: Redis connection string
      - key: WEB_URL
        configurable: true
        description: Public URL of the web frontend
      - key: CORS_ALLOWED_ORIGINS
        configurable: true
        description: Allowed CORS origins
      - key: ENABLE_SIGNUP
        default: "1"
        configurable: true
        description: Enable user signup
    volumes:
      - name: plane-uploads
        path: /code/plane/uploads
        size: 10240
    health_check:
      type: http
      path: /api/v1/
      port: 8000
      initial_delay: 30
      interval: 30
      timeout: 10
      retries: 3
    cpu: 300
    memory: 1024

  - name: plane-worker
    type: worker
    image: "makeplane/plane-backend:${VERSION}"
    command:
      - ./bin/worker
    env:
      - key: SECRET_KEY
        generator: password
        description: Django secret key
      - key: DATABASE_URL
        configurable: true
        description: PostgreSQL connection string
      - key: REDIS_URL
        configurable: true
        description: Redis connection string
    volumes:
      - name: plane-uploads
        path: /code/plane/uploads
        size: 10240
    cpu: 200
    memory: 512
