version: "1"

# Template metadata
name: gitea
description: Gitea is a lightweight, self-hosted Git service providing repository hosting, code review, issue tracking, and CI/CD workflows.
icon: https://raw.githubusercontent.com/go-gitea/gitea/main/public/assets/img/logo.svg
category: devops
tags:
  - devops
  - git
  - source-control
  - ci-cd
  - self-hosted

# Supported versions
versions:
  - "1.21"
  - "1.20"
  - "1.19"
defaultVersion: "1.21"

# Service definitions
services:
  - name: gitea
    type: web
    image: "gitea/gitea:${VERSION}"
    ports:
      - port: 3000
      - port: 22
    env:
      - key: GITEA__database__DB_TYPE
        value: postgres
        description: Database type
      - key: GITEA__database__HOST
        configurable: true
        description: PostgreSQL host and port (e.g., postgres:5432)
      - key: GITEA__database__NAME
        default: gitea
        configurable: true
        description: Database name
      - key: GITEA__database__USER
        default: gitea
        configurable: true
        description: Database username
      - key: GITEA__database__PASSWD
        generator: password
        description: Database password
      - key: GITEA__security__SECRET_KEY
        generator: password
        description: Secret key for encryption
      - key: GITEA__security__INTERNAL_TOKEN
        generator: password
        description: Internal API token
    volumes:
      - name: gitea-data
        path: /data
        size: 10240
    health_check:
      type: http
      path: /api/healthz
      port: 3000
      initial_delay: 30
      interval: 30
      timeout: 10
      retries: 3
    cpu: 200
    memory: 512
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 3000
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
