version: "1"

# Template metadata
name: nextcloud
description: Nextcloud is a self-hosted productivity platform providing file sync and share, collaborative document editing, calendars, contacts, and more.
icon: https://raw.githubusercontent.com/nextcloud/server/master/core/img/logo/logo.svg
category: storage
tags:
  - storage
  - file-sync
  - collaboration
  - office
  - cloud-storage

# Supported versions
versions:
  - "28"
  - "27"
  - "26"
defaultVersion: "28"

# Service definitions
services:
  - name: nextcloud
    type: web
    image: "nextcloud:${VERSION}"
    ports:
      - port: 80
    env:
      - key: POSTGRES_HOST
        configurable: true
        description: PostgreSQL host
      - key: POSTGRES_DB
        default: nextcloud
        configurable: true
        description: Database name
      - key: POSTGRES_USER
        default: nextcloud
        configurable: true
        description: Database username
      - key: POSTGRES_PASSWORD
        generator: password
        description: Database password
      - key: NEXTCLOUD_ADMIN_USER
        default: admin
        configurable: true
        description: Admin username
      - key: NEXTCLOUD_ADMIN_PASSWORD
        generator: password
        description: Admin password
      - key: NEXTCLOUD_TRUSTED_DOMAINS
        default: "localhost"
        configurable: true
        description: Space-separated list of trusted domains
      - key: OVERWRITEPROTOCOL
        default: "http"
        configurable: true
        description: Protocol for URL generation (http or https)
    volumes:
      - name: nextcloud-data
        path: /var/www/html
        size: 51200
    health_check:
      type: http
      path: /status.php
      port: 80
      initial_delay: 60
      interval: 30
      timeout: 10
      retries: 5
    cpu: 200
    memory: 512
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 80
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
