version: "1"

# Template metadata
name: db2
description: IBM Db2 is an enterprise-grade relational database management system known for its scalability, reliability, and advanced analytics capabilities.
icon: https://www.ibm.com/content/dam/adobe-cms/instana/media_logo/Db2.png
category: database
tags:
  - database
  - sql
  - relational
  - db2
  - ibm
  - enterprise

# Supported versions
versions:
  - "11.5.9.0"
  - "11.5.8.0"
defaultVersion: "11.5.9.0"

# Service definitions
services:
  - name: db2
    type: worker
    image: "ibmcom/db2:${VERSION}"
    ports:
      - port: 50000
    env:
      - key: LICENSE
        value: accept
        description: Accept IBM Db2 license agreement
      - key: DB2INSTANCE
        default: db2inst1
        configurable: true
        description: Db2 instance name
      - key: DB2INST1_PASSWORD
        generator: password
        description: Db2 instance owner password
      - key: DBNAME
        default: app
        configurable: true
        description: Default database name to create
    volumes:
      - name: db2-data
        path: /database
        size: 10240
    health_check:
      type: exec
      command: ["su", "-", "db2inst1", "-c", "db2 connect to ${DBNAME}"]
      initial_delay: 120
      interval: 30
      timeout: 10
      retries: 5
    cpu: 500
    memory: 4096
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 50000
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
