version: "1"

# Template metadata
name: mariadb
description: MariaDB is a community-developed, commercially supported fork of MySQL, offering high compatibility, enhanced features, and improved performance.
icon: https://raw.githubusercontent.com/docker-library/docs/master/mariadb/logo.png
category: database
tags:
  - database
  - sql
  - relational
  - mariadb
  - mysql-compatible

# Supported versions
versions:
  - "11.4"
  - "11.2"
  - "10.11"
  - "10.6"
defaultVersion: "11.4"

# Service definitions
services:
  - name: mariadb
    type: worker
    image: "mariadb:${VERSION}"
    ports:
      - port: 3306
    env:
      - key: MARIADB_ROOT_PASSWORD
        generator: password
        description: MariaDB root user password
      - key: MARIADB_USER
        default: app
        configurable: true
        description: MariaDB application user username
      - key: MARIADB_PASSWORD
        generator: password
        description: MariaDB application user password
      - key: MARIADB_DATABASE
        default: app
        configurable: true
        description: Default database name to create
    volumes:
      - name: mariadb-data
        path: /var/lib/mysql
        size: 10240
    health_check:
      type: exec
      command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
      initial_delay: 30
      interval: 10
      timeout: 5
      retries: 3
    cpu: 200
    memory: 512
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 3306
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
