version: "1"

# Template metadata
name: mysql
description: MySQL is the world's most popular open-source relational database management system, known for its speed, reliability, and ease of use.
icon: https://raw.githubusercontent.com/docker-library/docs/master/mysql/logo.png
category: database
tags:
  - database
  - sql
  - relational
  - mysql

# Supported versions
versions:
  - "8.4"
  - "8.0"
  - "5.7"
defaultVersion: "8.0"

# Variables
variables:
  # Database credentials
  - key: MYSQL_ROOT_PASSWORD
    type: secret
    description: MySQL root user password
    generator: password
  - key: MYSQL_USER
    type: string
    description: MySQL application user username
    default: app
  - key: MYSQL_PASSWORD
    type: secret
    description: MySQL application user password
    generator: password
  - key: MYSQL_DATABASE
    type: string
    description: Default database name to create
    default: app

# Service definitions
services:
  - name: mysql
    type: statefulset
    image: "mysql:${VERSION}"
    ports:
      - port: 3306
    env:
      - key: MYSQL_ROOT_PASSWORD
      - key: MYSQL_USER
      - key: MYSQL_PASSWORD
      - key: MYSQL_DATABASE
    volumes:
      - name: mysql-data
        path: /var/lib/mysql
        size: 10240
    health_check:
      type: exec
      command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      initial_delay: 30
      interval: 10
      timeout: 5
      retries: 3
    resources:
      cpu: 200
      memory: 512
    tcp_exposure:
      enabled: false
      port: 3306
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
