version: "1"

# Template metadata
name: postgres
description: PostgreSQL is a powerful, open-source object-relational database system with a strong reputation for reliability, feature robustness, and performance.
icon: https://raw.githubusercontent.com/docker-library/docs/master/postgres/logo.png
category: database
tags:
  - database
  - sql
  - relational
  - postgresql

# Supported versions
versions:
  - "18"
  - "17"
  - "16"
  - "15"
  - "14"
defaultVersion: "17"

# Variables
variables:
  # Database credentials
  - key: POSTGRES_USER
    type: string
    description: PostgreSQL superuser username
    default: postgres
  - key: POSTGRES_PASSWORD
    type: secret
    description: PostgreSQL superuser password
    generator: password
  - key: POSTGRES_DB
    type: string
    description: Default database name to create
    default: app


# Service definitions
services:
  - name: postgres
    type: statefulset
    image: "postgres:${VERSION}-alpine"
    ports:
      - port: 5432
    env:
      - key: POSTGRES_USER
      - key: POSTGRES_PASSWORD
      - key: POSTGRES_DB
    volumes:
      - name: postgres-data
        path: /var/lib/postgresql/data
        size: 10240
    health_check:
      type: exec
      command: ["pg_isready", "-U", "${POSTGRES_USER}"]
      initial_delay: 10
      interval: 10
      timeout: 5
      retries: 3
    resources:
      cpu: 100
      memory: 256
    tcp_exposure:
      enabled: fase
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 5432
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
