version: "1"

# Template metadata
name: redis
description: Redis is an open-source, in-memory data structure store used as a database, cache, message broker, and streaming engine.
icon: https://raw.githubusercontent.com/docker-library/docs/master/redis/logo.png
category: cache
tags:
  - cache
  - database
  - in-memory
  - key-value
  - redis

# Supported versions
versions:
  - "7.4"
  - "7.2"
  - "6.2"
defaultVersion: "7.2"

# Service definitions
services:
  - name: redis
    type: worker
    image: "redis:${VERSION}-alpine"
    ports:
      - port: 6379
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
      - --requirepass
      - ${REDIS_PASSWORD}
    env:
      - key: REDIS_PASSWORD
        generator: password
        description: Redis authentication password
    volumes:
      - name: redis-data
        path: /data
        size: 1024
    health_check:
      type: exec
      command: ["redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      initial_delay: 5
      interval: 10
      timeout: 3
      retries: 3
    cpu: 50
    memory: 128
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 6379
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
