version: "1"

# Template metadata
name: posthog
description: PostHog is an open-source product analytics platform providing event tracking, session replay, feature flags, A/B testing, and user surveys.
icon: https://raw.githubusercontent.com/PostHog/posthog/master/frontend/public/hedgehog.svg
category: analytics
tags:
  - analytics
  - product-analytics
  - feature-flags
  - ab-testing
  - session-replay

# Supported versions
versions:
  - "release"
  - "latest"
defaultVersion: "release"

# Service definitions
services:
  - name: posthog
    type: web
    image: "posthog/posthog:${VERSION}"
    ports:
      - port: 8000
    env:
      - key: SECRET_KEY
        generator: password
        description: Django secret key
      - key: DATABASE_URL
        configurable: true
        description: PostgreSQL connection string
      - key: REDIS_URL
        configurable: true
        description: Redis connection string
      - key: SITE_URL
        default: "http://localhost:8000"
        configurable: true
        description: Public URL of the PostHog instance
      - key: DISABLE_SECURE_SSL_REDIRECT
        default: "true"
        configurable: true
        description: Disable SSL redirect for development
      - key: IS_BEHIND_PROXY
        default: "true"
        configurable: true
        description: Enable when behind a reverse proxy
    volumes:
      - name: posthog-data
        path: /var/lib/posthog
        size: 10240
    health_check:
      type: http
      path: /_health
      port: 8000
      initial_delay: 60
      interval: 30
      timeout: 10
      retries: 5
    cpu: 500
    memory: 2048
    tcp_exposure:
      enabled: false
      hostname: "${NAME}-${STAGE}.${DOMAIN}"
      port: 8000
      tls:
        mode: terminate
      gateway:
        name: dms-gateway
        namespace: dms-system
